name: eni_web
description: "Eniware Systems Web embedding utilities"
version: 2.0.5
homepage: https://eniware-systems.de
publish_to: https://gitea.eniware-systems.de/api/packages/eni-flutter/pub

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.32.0"

dependencies:
  flutter:
    sdk: flutter

  eni_svc:
    git:
      url: https://github.com/eniware-systems/eni_svc.git
      ref: main
  eni_utils:
    git:
      url: https://github.com/eniware-systems/eni_utils.git
      ref: main

  js: ^0.7.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.2
